export const URL = "http://127.0.0.1/api/";

export const GETTASKS_ATTEMPT = "GETTASKS_ATTEMPT";
export const GETTASKS_SUCCESS = "GETTASKS_SUCCESS";
export const GETTASKS_FAILED = "GETTASKS_FAILED";

export const CREATETASKS_ATTEMPT = "CREATETASKS_ATTEMPT";
export const CREATETASKS_SUCCESS = "CREATETASKS_SUCCESS";
export const CREATETASKS_FAILED = "CREATETASKS_FAILED";

export const DELETETASKS_ATTEMPT = "DELETETASKS_ATTEMPT";
export const DELETETASKS_SUCCESS = "DELETETASKS_SUCCESS";
export const DELETETASKS_FAILED = "DELETETASKS_FAILED";

export const SEARCHTASKS_ATTEMPT = "SEARCHTASKS_ATTEMPT";
export const SEARCHTASKS_SUCCESS = "SEARCHTASKS_SUCCESS";
export const SEARCHTASKS_FAILED = "SEARCHTASKS_FAILED";